name : Android Application Build Process
run-name : Application building is starting
on : [push]
jobs: 
  Setup-python-env:
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v4.2.2
       - uses: actions/setup-python@v5
         with: 
           python-version:'3.12'
       - run: sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
